services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-10.4.2}
    user: ":"
    ports:
      - ${MONITORING_PORT_GRAFANA:-3000}:3000
    networks: [dvnode]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/alerts:/etc/grafana/provisioning/alerting
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped
