include:
- el/docker-compose-el-nethermind.yml
- cl/docker-compose-cl-lighthouse.yml
- vc/docker-compose-vc-lodestar.yml
- docker-compose-mev-boost.yml
- docker-compose-charon.yml
- docker-compose-prometheus.yml
- docker-compose-grafana.yml

networks:
  dvnode:
