services:
  el:
    container_name: el-nethermind
    image: nethermind/nethermind:${NETHERMIND_VERSION:-1.25.4}
    restart: unless-stopped
    ports:
      - ${NETHERMIND_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${NETHERMIND_PORT_P2P:-30303}:30303/udp # P2P UDP
    command: |
      --config=${NETWORK:-holesky}
      --datadir=data
      --JsonRpc.Enabled=true
      --JsonRpc.JwtSecretFile="/root/jwt/jwt.hex"
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --Sync.SnapSync=true
      --HealthChecks.Enabled=true
      --Metrics.Enabled=true
      --Metrics.ExposePort=8008
    networks: [dvnode]
    volumes:
      - ./data/nethermind:/nethermind/data
      - ./jwt:/root/jwt
