services:
  cl:
    container_name: cl-lighthouse
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-v5.1.3}
    ports:
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/tcp   # P2P TCP
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/udp   # P2P UDP
    command: |
      lighthouse bn
      --network=${NETWORK:-holesky}
      --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL:-https://checkpoint-sync.holesky.ethpandaops.io}
      --execution-endpoint=http://nethermind:8551
      --execution-jwt=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --builder=http://mev-boost:18550
      --http
      --http-address=0.0.0.0
      --http-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=5054
      --metrics-allow-origin="*"
    networks: [dvnode]
    volumes:
      - ./data/lighthouse:/opt/app/beacon
      - ./jwt:/opt/jwt
    restart: unless-stopped
